### PR TITLE
chore: update the status value strings of nim cache and nim services

### PR DESCRIPTION
**Pull request by slu2011**

### CODE REVIEW

**Review by mikemckiernan — COMMENTED** [review]
Is that really all there is to it?  I chickened out because I noticed some more complicated work in https://github.com/NVIDIA/k8s-nim-operator/blob/main/internal/conditions/conditions.go.

**Comment by slu2011** [comment]
> Is that really all there is to it? I chickened out because I noticed some more complicated work in https://github.com/NVIDIA/k8s-nim-operator/blob/main/internal/conditions/conditions.go.

I believe conditions.go is all good (status values consistent with k8s api). Just updating the status value strings of nimcache / nimservices should be enough to fix the issue.

**Comment by slu2011** [comment]
> > Is that really all there is to it? I chickened out because I noticed some more complicated work in https://github.com/NVIDIA/k8s-nim-operator/blob/main/internal/conditions/conditions.go.
> 
> I believe conditions.go is all good (status values consistent with k8s api). Just updating the status value strings of nimcache / nimservices should be enough to fix the issue.

**Review by visheshtanksale — APPROVED** [review]

**Comment by mikemckiernan** [comment]
> > Is that really all there is to it? I chickened out because I noticed some more complicated work in https://github.com/NVIDIA/k8s-nim-operator/blob/main/internal/conditions/conditions.go.
> 
> I believe conditions.go is all good (status values consistent with k8s api). Just updating the status value strings of nimcache / nimservices should be enough to fix the issue.

Delightful!  So sorry that I was cowardly.  :)

**Pull request merged**
